---
- hosts: all
  sudo: yes
  tasks:
    - yum: pkg=python-setuptools state=installed
    - command: easy_install pip
      args:
        creates: /usr/bin/pip
    # CentOS6 + easy_install is broken, so upgrade it over pip
    - command: pip install setuptools --no-use-wheel --upgrade
    - pip: name=meld3 version=1.0.2
    - pip: name=supervisor version=3.1.1
    - copy: src=../files/supervisord.init dest=/etc/init.d/supervisord owner=root mode=755
    - service: name=supervisord enabled=true
    - copy: src=../files/supervisord.conf dest=/etc/supervisord.conf owner=root mode=644
      notify:
        - restart supervisord
  handlers:
    - name: restart supervisord
      action: service name=supervisord state=restarted
