---
- hosts: all
  remote_user: ec2-user
  sudo: yes
  tasks:
    - yum: pkg=git state=installed
    - yum: pkg=mercurial state=installed
    - yum: pkg=bzr state=installed
    - command: "curl -L -O  http://golang.org/dl/go1.3.linux-amd64.tar.gz"
      args:
        chdir: /tmp
        creates: /usr/local/go
    - command: "tar -C /usr/local -xzf go1.3.linux-amd64.tar.gz"
      args:
        chdir: /tmp
        creates: /usr/local/go
    - copy: src=../files/golang.sh dest=/etc/profile.d/golang.sh mode=644 owner=root group=root
    - command: "/usr/bin/gem install --no-rdoc --no-ri gondler -v 0.2.0"
      args:
        creates: /usr/local/bin/gondler
    - command: /home/isucon/env.sh ./build.sh
      args:
        chdir: /home/isucon/webapp/go
    - command: chown -R isucon:isucon /home/isucon/gocode
